### PR TITLE
[ NEW UI ] implement redesign of UI

### PR DESCRIPTION
**Pull request by dpereskokov**
Fixes: #176

### CODE REVIEW

**Comment by leoneparise** [comment]
This PR is still valid @dpereskokov ?

**Comment by dpereskokov** [comment]
> This PR is still valid @dpereskokov ?
Yeah, it accumulates all the sub PRs. All the work on redesign is merged here. When I finish with it we will merge the whole work to master.

**Comment by dpereskokov** [comment]
#176 is the main issue and has many sub issues

**Comment by leoneparise** [comment]
I won't be able to review 6k lines of code. Let's merge it if everything is ok.

**Pull request merged**
